# Generated by Django 3.0.3 on 2020-02-08 13:15

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('icon_media_key', models.UUIDField()),
            ],
        ),
    ]
