# Generated by Django 3.0.3 on 2020-02-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon_media_key',
        ),
        migrations.AddField(
            model_name='user',
            name='icon_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
