version: "3"
services:
  web_server:
    build:
      context: server
      dockerfile: prod.Dockerfile
    environment:
      LOCAL_ADDRESS: $LOCAL_ADDRESS
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/var/static/api/admin/
      - $SANDBOX_DIRECTORY_PATH:/var/sandbox
      - /var/www/letsencrypt-webroot:/var/www/letsencrypt-webroot
      - /etc/letsencrypt/archive/api.selelab.com:/etc/letsencrypt/live/api.selelab.com
    depends_on:
      - api
    command: >
      /bin/sh -c
      "envsubst '
      $$LOCAL_ADDRESS
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    restart: always
volumes:
  admin-front:
    driver: local
