version: '3'
services:
  python:
    build: ./web
    entrypoint:
      - /bin/sh
      - entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./web/:/var/app/
    # depends_on:
    #   - "docker_db"
    networks:
     - "default"
     - "db_sharing"
networks:
  default:
    external: false
  db_sharing:
    external: true
