version: '3'
services:
  web_server:
    build:
      context: apache
    ports:
      - "80:80"
    volumes:
      - ./static:/var/static
      - ../web/build:/var/react
      - "./front/dist:/var/admin-front"
    depends_on:
      - api
  redis:
    image: redis
    volumes:
      - "./data/redis:/data"
  api:
    build:
      context: api
    environment:
      - DJANGO_SETTINGS_MODULE=web.settings
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DJANGO_FORCE_SCRIPT_NAME=$DJANGO_FORCE_SCRIPT_NAME
      - DEBUG=False
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_DB=$REDIS_DB
      - REDIS_PASS=$REDIS_PASS
    entrypoint:
      - /bin/sh
      - prod_entrypoint.sh
    expose:
      - "8001"
    volumes:
      - ./api/:/var/app/
      - ./static/:/var/static
