version: '3'
services:
  web_server:
    build:
      context: apache
    ports:
      - "80:80"
    volumes:
      - ./static:/var/static/api/admin/
      - ../contests/static:/var/contests/static/
      - ../contests/front/dist:/var/contests/dist/
      - ../web/build:/var/react
      - ./front/dist:/var/admin-front
      - $SANDBOX_DIRECTORY_PATH:/var/sandbox
    depends_on:
      - api
    restart: always
  api:
    build:
      context: api
    environment:
      - DJANGO_SETTINGS_MODULE=web.settings
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DJANGO_FORCE_SCRIPT_NAME=$DJANGO_FORCE_SCRIPT_NAME
      - DJANGO_DEBUG=$DJANGO_DEBUG
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_DB=$REDIS_DB
      - REDIS_PASS=$REDIS_PASS
    entrypoint:
      - /bin/sh
      - entrypoint.sh
    ports:
      - "8001:8001"
    volumes:
      - ./api/:/var/app/
      - ./static/:/var/static
      - ./log/django/:/var/log/django/
    restart: always
