# Generated by Django 3.0.5 on 2020-04-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='content_type',
            field=models.CharField(default='application/octet-stream', max_length=256),
            preserve_default=False,
        ),
    ]
