# Generated by Django 3.0.3 on 2020-02-18 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('accounting', '0004_project_description'), ('accounting', '0005_auto_20200218_1827'), ('accounting', '0006_auto_20200218_1938'), ('accounting', '0007_auto_20200218_1953')]

    dependencies = [
        ('accounting', '0003_auto_20200215_0850'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='purchase',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='projectapproval',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
