# Generated by Django 3.0.4 on 2020-03-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_project_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='projectapproval',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
