# Generated by Django 3.0.4 on 2020-03-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20200327_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_created', 'id']},
        ),
    ]
