# Generated by Django 3.0.4 on 2020-03-30 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20200329_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectapproval',
            options={'ordering': ['-date_created', 'id']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date_created', 'id']},
        ),
        migrations.AddField(
            model_name='projectapproval',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
