# Generated by Django 3.0.4 on 2020-04-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20200405_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='evidence_media_key',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='returned',
        ),
    ]
