# Generated by Django 3.0.4 on 2020-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20200407_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapproval',
            name='comment',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='comment',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
