# Generated by Django 3.0.3 on 2020-02-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('accounting', '0001_initial'), ('accounting', '0002_auto_20200208_0031'), ('accounting', '0003_auto_20200208_0847'), ('accounting', '0004_auto_20200208_0857')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('icon_media_key', models.UUIDField()),
            ],
        ),
    ]
